<?php include 'includes/header.php'?>

<section class="container">
    <article class="about">
        <h1 class="the-font">Sobre</h1>
        <p>DELION DE OLIVEIRA, NASCIDO EM 31/03/1931, NATURAL DE JACAREÍ/ SP, FILHO DE JUVENAL DE OLIVEIRA E OLIVIA MIGUEL DE OLIVEIRA, SEGUNDO FILHO DE CINCO IRMÃOS.<br>
FOI CASADO DURANTE 43 ANOS COM NILSE MARIA AZEVEDO DE OLIVEIRA E TIVERAM DOIS FILHOS, MARCIA E DELION JR E SETE NETOS, RODRIGO, THIAGO, JENIFFER, DENISE, ANA LUÍSA, BRUNO E LEONARDO. O SR. DELION CURSOU E CONCLUIU OS ESTUDOS NA ESCOLA MUNICIPAL AGRÍCOLA DE JACAREÍ. A CARREIRA PROFISSIONAL FOI PAUTADA POR UMA GRANDE DIVERSIDADE. ELE TRABALHOU NUMA LOJA LOCAL DA CIDADE DE JACAREÍ CHAMADA MICHEL, POSTERIORMENTE TRABALHOU NO BANCO MERCANTIL DE SÃO PAULO, TRABALHOU TAMBÉM NO SETOR DE ALMOXARIFADO DE UMA FÁBRICA GATES E POR FIM FOI GERENTE DE UMA LANCHONETE, SENDO QUE ESTE ÚLTIMO TRABALHO ERA EXPLICITAMENTE OQUE LHE DAVA MAIS PRAZER, POIS ERA COMPLETAMENTE LIGADO AO SETOR GASTRONÔMICO.<br>
A VIDA TODA O SR. DELION FEZ EXTRAS DE GARÇON, POIS TINHA UM DOM ÚNICO, QUE ERA O TRATO COM O PÚBLICO. O SEU MAIOR SONHO ERA TER UM ESTABELECIMENTO COMERCIAL PRÓPRIO LIGADO A GASTRONOMIA PARA JUSTAMENTE TER ESSA PROXIMIDADE COM O PÚBLICO, MAS INFELIZMENTE NÃO FOI POSSÍVEL. ELE FALECEU NO DIA 30/05/1996 NA SUA CIDADE NATAL DEIXANDO UM LEGADO PARA TODOS: O BOM CARÁTER, A HONESTIDADE, O TRABALHO E O RESPEITO À FAMÍLIA FORMANDO UM CONJUNTO DE FATORES QUE ESTÃO DIRETAMENTE LIGADOS AO ALCANCE DE UM SONHO. ESTA UMA SINGELA HISTÓRIA E UMA GRANDE HOMENAGEM QUE A "DELION CAFÉ" PRESTA A ESTE GRANDE HOMEM QUE NOS DEIXA UM LEGADO DE SER HUMANO IDÔNEO PARA COM TODOS E SAUDADES ETERNAS.<br><br>
OBRIGADO POR TUDO SR. DELION DE OLIVEIRA.<br>
HOMENAGEM DE FILHOS E NETOS.</p>
    </article>
    <aside class="sidebar">
        <h2 class="the-font">Endereço</h2>
        <p>Rua Quintino Bocaiuva 850, sala 04 - Centro</p>
        <p>Telefones: (045) 3027-0059</p>
        <p>E-mail: contato@delioncafe.com.br</p>
    </aside>
</section>

<?php include 'includes/footer.php'?>
