<?php

include_once $_SERVER['DOCUMENT_ROOT']."/config.php"; 


class InfoBip{

    private $base_url = BASE_URL_INFOBIP;
    private $apikey = APIKEY_INFOBIP_SMS;
    
    
    function enviaSMS($telefone, $cod_sms){
        
        $curl = curl_init();

        curl_setopt_array($curl, array(
            CURLOPT_URL => $this->base_url."/sms/2/text/single",
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => "{ \"from\":\"DelionCafe\", \"to\":\"".$telefone."\", \"text\":\"Delion Cafe - Codigo de verificacao: ".$cod_sms."\" }",
            CURLOPT_HTTPHEADER => array(
                "accept: application/json",
                "authorization: ".$this->apikey,//get apiky generated by infobip
                "content-type: application/json"
            ),
        ));

        $response = curl_exec($curl);
        $err = curl_error($curl);

        curl_close($curl);

        if ($err) {
            echo $err;
            return "cURL Error #:" . $err;
        } else {
            return $response;
        }
    }
}

?>
	